### post request

POST  http://localhost:5000/info/add
Content-Type: application/json

{
    "username":"person 1",
    "description": "posting",
    "date": "2020-08-01T02:22:49.052Z"
}

### testing get request

GET http://localhost:5000/users/

### testing crud

GET http://localhost:5000/info/