### post request

POST  http://localhost:5000/info/add
Content-Type: application/json

{
    "username":"person 1",
    "description": "posting",
    "date": "2020-08-01T02:22:49.052Z"
}

### testing get request

GET http://localhost:5000/users/

### testing crud

GET http://localhost:5000/info/

### testing GET products

GET http://localhost:5000/products/

### testing POST new product

POST http://localhost:5000/products/add
Content-Type: application/json

{
    "sku": "3D57JJFF0",
    "quantity": 1,
    "name": "Wine Tumbler",
    "nameTranslated": {
        "en": "hello",
        "es": "hola"
    },
    "price": 19.99,
    "compareToPrice": 5.00,
    "isShippingRequired": true,
    "categoryIds": [1, 2],
    "weight": 5,
    "enabled": true,
    "description": "Stainless Steel Wine Tumbler for all your Winetumbling needs!",
    "productClassId": 4,
    "created": "user1",
    "fixedShippingRateOnly": false,
    "fixedShippingRate": 20,
    "brand": "American Wino",
    "tax":{
        "enabledManualTaxes": [1]
    },
    "optionsType": "type"
       
}